project:
  type: book

book:
  title: "Dissertation"
  author: "Sergio Pérez-Limón"
  date: "3/10/2023"
  chapters:
    - index.qmd
    - intro.qmd
    - part: MAGIC.qmd
    - part: CML.qmd
      chapters:
        - "CML-2023-03-12-23_Highland_Ameca_Experimental_Design.qmd"
    - PT.qmd
    - AMF.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: book



