project:
  type: book

book:
  title: "Dissertation"
  author: "Sergio Pérez-Limón"
  date: "3/10/2023"
  chapters:
    - index.qmd
    - intro.qmd
    - MAGIC.qmd
    - CML.qmd
    - PT.qmd
    - AMF.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: book



